version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: phppdo
        volumes:
            - ./code:/code
        networks:
            - code-network
    database:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=example
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
